import ast
import io
import pathlib
import re
import tokenize
from typing import List

_ROOT = pathlib.Path(__file__).resolve().parents[1]
_GUARD = pathlib.Path(__file__).resolve()
_EMOJI = re.compile("[\U0001f000-\U0001faff\u2600-\u27bf\ufe0f]")
_PHRASES = [
    "reproduction of",
    "based on the paper",
    "re-implementation",
    "following the authors",
    "as described by",
    "generated by",
    "ai-assisted",
    "auto-derived",
    "auto-driven",
    "state-of-the-art",
    "cutting-edge",
    "seamlessly",
    "leveraging",
    "utilize",
    "delve",
    "holistic",
    "meticulously",
    "it's worth noting",
    "in conclusion",
    "comprehensive",
    "placeholder",
]


def _python_files() -> List[pathlib.Path]:
    collected: List[pathlib.Path] = []
    for base in ("econcausal", "trials"):
        for path in (_ROOT / base).rglob("*.py"):
            if path.resolve() != _GUARD:
                collected.append(path)
    return collected


def test_no_comments_and_no_docstrings():
    for path in _python_files():
        source = path.read_text(encoding="utf-8")
        for token in tokenize.generate_tokens(io.StringIO(source).readline):
            assert token.type != tokenize.COMMENT, f"comment found in {path}"
        tree = ast.parse(source)
        for node in ast.walk(tree):
            if isinstance(node, (ast.Module, ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                assert ast.get_docstring(node) is None, f"docstring found in {path}"


def test_no_emoji_or_marketing_language():
    targets = _python_files() + [_ROOT / "README"]
    for path in targets:
        text = path.read_text(encoding="utf-8")
        assert not _EMOJI.search(text), f"emoji found in {path}"
        lowered = text.lower()
        for phrase in _PHRASES:
            assert phrase not in lowered, f"forbidden phrase {phrase!r} in {path}"
